import Head from 'next/head';
import { useAppDispatch, useAppSelector } from '@store';
import { incremented, incrementBy } from '@features';
import { useGetMoveBattleStyleByNameQuery } from '@services';
import styles from '../styles/Home.module.css';

export default function Home() {
  const counter = useAppSelector((state) => state.counter.value);
  const dispatch = useAppDispatch();
  const { data, isFetching } = useGetMoveBattleStyleByNameQuery(1);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <button onClick={() => dispatch(incremented())} type="button" aria-label="Increment by 1">
            Increment by 1
          </button>
          <button onClick={() => dispatch(incrementBy(10))} type="button" aria-label="Add 10">
            Increment by 10
          </button>
          <span>{counter}</span>
        </div>
        <div>{isFetching}</div>
        <div>
          <p>{data?.id}</p>
          <p>{data?.name}</p>
          {data?.names.map(({ name, language }) => {
            return (
              <div key={language.name}>
                <p>{name}</p>
                <a href={language.url}>{language.name}</a>
              </div>
            );
          })}
        </div>
      </main>
    </div>
  );
}
